exp:
  seed: 42  #defult  42
  name: csa_net
  rank: 0
  ngpus_per_node: 2
  world_size: 2
  checkpoint: ''  # none
  eval: False
  resume: False

defaults:
  - _self_
  - cap_generator@model.cap_generator: parallel # parallel, sequential, concat

dataset:
  overfit: False #overfit True for debug
  ann_root: '${oc.env:DATA_ROOT}/annotations'
  img_root: '${oc.env:DATA_ROOT}'
  hdf5_path: '${oc.env:DATA_ROOT}/all_splits.h5' # this is used for freezed extractor; fast to train.
  vocab_path: '${oc.env:DATA_ROOT}/annotations/vocab.json'
  use_rel_feat: ${model.use_rel_feat}
  use_reg_feat: ${model.use_reg_feat}

  transform_cfg:
    size: [384, 640] # (h, w)
    resize_name: maxwh # normal, minmax, maxwh; maxwh is computationally friendly for training
    randaug: True

model:
  use_rel_feat: True   #defult True
  use_csa_net: True   #defult True
  use_reg_feat: True
  csa_feat_dim: 1024
  frozen_stages: 2
  beam_size: 5
  beam_len: 20
  dropout: 0.2
  attn_dropout: 0.2

  vocab_size: 10201
  max_len: 54
  pad_idx: 1
  bos_idx: 2
  eos_idx: 3
  d_model: 512
  n_heads: 8

  csa_net:
    n_layers: 3

  detector: 
    checkpoint: './coco_caption/detector_checkpoint_4ds.pth'
    d_model: 512
    dim_feedforward: 1024
    num_heads: 8
    num_layers: 6
    num_levels: 4
    num_points: 4
    num_queries: 150
    num_classes: 1849
    dropout: 0.1
    activation: 'relu'
    return_intermediate: True
    with_box_refine: True


optimizer:
  warmup_init_lr: 8e-6
  min_lr: 8e-5
  xe_lr: 8e-5 # if xe_lr == min_lr, then CosineAnneal doesn't affect anymore.
  sc_lr: 4e-6
  xe_backbone_lr: 8e-6
  sc_backbone_lr: 4e-6
  weight_decay: 0.01
  beta_1: 0.9
  beta_2: 0.99
  batch_size: 16 # defulat 50  bs4->14G
  num_workers: 2
  freezing_xe_epochs: 0
  freezing_sc_epochs: 0
  finetune_xe_epochs: 15
  finetune_sc_epochs: 30
  freeze_detector: False
  freeze_backbone: False

hydra:
  run:
    dir: output/${exp.name}  # saving model directory
  output_subdir: ./ # directory for saving the yaml configs
  job:
    config:
      override_dirname:
        exclude_keys:
          - exp.name
